name: Deploy Compute Networking

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Two roots to run
      matrix:
        workdir:
          - environment/production

    name: Apply (${{ matrix.workdir }})

    steps:
      - uses: actions/checkout@v4


      - name: Authenticate to GCP (Service Account JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Fmt (repo)
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan.out -input=false -var="project_id=${{ secrets.GCP_PROJECT_ID }}"


      - name: Terraform Apply (push only)
        if: github.event_name == 'push'
        run: terraform apply -input=false tfplan.out
